# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-12 21:51
from __future__ import unicode_literals

import Email.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Email.models.email_attachment_upload_location)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from', models.CharField(max_length=255)),
                ('to', models.EmailField(max_length=254)),
                ('html', models.TextField()),
                ('sender_ip', models.GenericIPAddressField()),
                ('subject', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Email.Email'),
        ),
    ]
