# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='sender_ip',
        ),
        migrations.AlterField(
            model_name='email',
            name='from',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='html',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.EmailField(editable=False, max_length=254),
        ),
    ]
