# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0002_auto_20160913_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.EmailField(max_length=254),
        ),
    ]
