# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-26 05:29
from __future__ import unicode_literals

import Core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('member_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'contact_information',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'contact us',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, validators=[Core.models.event_validator])),
                ('pic_path', models.FileField(default=None, null=True, upload_to=Core.models.events_upload_location)),
                ('small_pic_path', models.FileField(default=None, null=True, upload_to=Core.models.events_upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('presently_at', models.CharField(blank=True, max_length=225)),
                ('is_alumni', models.BooleanField(default=False)),
                ('batch', models.IntegerField()),
                ('pic_path', models.FileField(default=None, null=True, upload_to=Core.models.members_upload_location)),
                ('facebook', models.CharField(default=None, max_length=225, null=True)),
                ('github', models.CharField(default=None, max_length=225, null=True)),
                ('linkedin', models.CharField(default=None, max_length=225, null=True)),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Designation')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'ordering': ['batch'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('completion_year', models.IntegerField(default=None, null=True)),
                ('image_path', models.FileField(default=None, null=True, upload_to=Core.models.projects_upload_location)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('student_number', models.CharField(max_length=8)),
                ('hosteler', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Branch')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Event')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Year'),
        ),
        migrations.AddField(
            model_name='member',
            name='technology',
            field=models.ManyToManyField(to='Core.Technology'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set([('student_number', 'event')]),
        ),
    ]
