# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),
                ('presently_at', models.CharField(max_length=225)),
                ('is_alumni', models.BooleanField(default=False)),
                ('batch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='technology',
            field=models.ManyToManyField(to='Core.Technology'),
        ),
    ]
