# Generated by Django 3.2.4 on 2021-06-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='other_handles',
            new_name='account_handles',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='skills',
        ),
        migrations.AddField(
            model_name='registration',
            name='about_yourself',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='registration',
            name='experience',
            field=models.CharField(choices=[('no', 'No Experience'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='no', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='familiar_w_tools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='insta_improvement',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='why_attend',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='registration',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.year'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='year',
            name='value',
            field=models.IntegerField(choices=[(1, '1st year'), (2, '2nd year'), (3, '3rd year'), (4, '4th year')]),
        ),
    ]
