# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Designation'),
        ),
    ]
