# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20160710_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Designation'),
        ),
        migrations.AlterField(
            model_name='members',
            name='presently_at',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='members',
            name='technology',
            field=models.ManyToManyField(null=True, to='Core.Technology'),
        ),
    ]
