# Generated by Django 3.2.4 on 2021-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210615_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='familiar_w_tools',
        ),
        migrations.AddField(
            model_name='registration',
            name='design_tools',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(max_length=7),
        ),
    ]
