# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20160710_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
    ]
