# Generated by Django 3.2.4 on 2021-06-16 13:23

import Core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20210615_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='whatsapp_no',
        ),
        migrations.AddField(
            model_name='registration',
            name='your_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='files',
            field=models.FileField(default=None, null=True, upload_to=Core.models.events_upload_location, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
