# Generated by Django 3.2.4 on 2021-09-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20210616_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Core.domain'),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Core.gender'),
        ),
        migrations.AddField(
            model_name='registration',
            name='hacker_rank_username',
            field=models.CharField(blank=True, help_text='Your HackerRank username. Please create an account on HackerRank.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(default=1111111111, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='roll_no',
            field=models.CharField(default=1111111111111, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='skills',
            field=models.CharField(default='html/css', help_text='Skills like HTML, CSS, Java...', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='college_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Core.year'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='your_work',
            field=models.TextField(blank=True, help_text='Links to your work or coding profiles.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='about_yourself',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='account_handles',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='design_tools',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='insta_improvement',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='why_attend',
        ),
    ]
