# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pic_path',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
    ]
