# Generated by Django 3.2.4 on 2021-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20210903_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
