# Generated by Django 3.2.4 on 2022-04-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20220426_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mail_sent_status',
            field=models.BooleanField(default=False),
        ),
    ]
