# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0007_auto_20160728_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
