# Generated by Django 3.2.4 on 2022-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_registration_mail_sent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
