# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models

import Core.models


class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0008_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True,
                                          upload_to=Core.models.upload_location)),
            ],
        ),
    ]
