# Generated by Django 3.2.4 on 2022-09-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_registration_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='behance_username',
            field=models.CharField(blank=True, help_text='Your Behance username. Please create an account on Behance.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='github_username',
            field=models.CharField(blank=True, help_text='Your Github username. Please create an account on Github.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Core.year'),
        ),
    ]
