# Generated by Django 3.2.4 on 2022-04-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_auto_20220423_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='whatsapp',
        ),
    ]
