# Generated by Django 3.2.4 on 2022-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_registration_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=225)),
            ],
        ),
    ]
