# Generated by Django 3.2.4 on 2022-09-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_auto_20220906_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='is_hosteler',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
