# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-29 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0009_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
    ]
