# Generated by Django 3.2.4 on 2022-04-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='student_number',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
