# Generated by Django 3.2.4 on 2022-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_auto_20220425_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_hosteler',
            field=models.BooleanField(default=False),
        ),
    ]
