# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_auto_20160730_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='technology',
            field=models.ManyToManyField(to='Core.Technology'),
        ),
    ]
