# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_branch_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(max_length=3),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
