# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_auto_20160730_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['batch'], 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 31, 3, 40, 30, 857247, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.IntegerField(unique=True),
        ),
    ]
