# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0017_auto_20160731_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
