# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models

import Core.models


class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0019_auto_20160801_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic_path',
            field=models.FileField(default=None, null=True,
                                   upload_to=Core.models.members_upload_location),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.FileField(default=None, null=True,
                                   upload_to=Core.models.projects_upload_location),
        ),
    ]
