# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.Event'),
            preserve_default=False,
        ),
    ]
