# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 17:26
from __future__ import unicode_literals

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_registration_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, validators=[Core.models.event_validator]),
        ),
    ]
