# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 17:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0023_auto_20160901_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='Core.Branch'),
        ),
    ]
