# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_branch_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Gender'),
        ),
    ]
