# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_auto_20160901_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Year'),
        ),
    ]
