# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0029_year_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student_number',
            field=models.CharField(max_length=8),
        ),
    ]
