# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-27 18:49
from __future__ import unicode_literals

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0033_auto_20170125_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pic_path',
            field=models.FileField(default=None, null=True, upload_to=Core.models.events_upload_location),
        ),
    ]
