# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-28 13:11
from __future__ import unicode_literals

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0034_event_pic_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False, validators=[Core.models.event_validator])),
            ],
        ),
    ]
