# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0036_delete_external'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'contact_information'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
