# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-25 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0038_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Blog', max_length=80),
        ),
    ]
