# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-30 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0040_auto_20170925_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 9, 30, 14, 56, 24, 707006, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
