# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-16 07:57
from __future__ import unicode_literals

import Core.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0042_auto_20180805_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(default=None, null=True, upload_to=Core.models.events_upload_location)),
                ('name', models.CharField(max_length=80)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_allowed', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=100)),
                ('text', ckeditor.fields.RichTextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Event')),
            ],
        ),
    ]
