# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-22 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0043_emailattachment_emailcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='codechef_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='codechef_team_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='university_rollno',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
