# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-22 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0044_auto_20190122_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='second_branch',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='second_branch', to='Core.Branch'),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_codechef_handle',
            field=models.CharField(blank=True, default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_contact',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_email',
            field=models.EmailField(default='1@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_gender',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='second_gender', to='Core.Gender'),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_hosteler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_name',
            field=models.CharField(default='1', max_length=225),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_student_number',
            field=models.CharField(default='1', max_length=8),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_university_rollno',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='second_year',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='second_year', to='Core.Year'),
        ),
    ]
