# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-09-11 16:15
from __future__ import unicode_literals

import Core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0046_auto_20190216_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=4)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^[56789]\\d{9}$')])),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.CharField(blank=True, choices=[('22 September(Sunday)', '22 September(Sunday)'), ('29 September(Sunday)', '29 September(Sunday)'), ('2  October(Sunday)', '2 October(Sunday)')], max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='name',
            field=models.CharField(max_length=80, validators=[Core.validators.validate_file_extension]),
        ),
    ]
