# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-09-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0047_auto_20190911_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='message',
            field=models.TextField(default='LOVE-PEACE-CODE', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='testimonial',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='date',
            field=models.CharField(blank=True, choices=[('22 September(Sunday)', '22 September(Sunday)'), ('29 September(Sunday)', '29 September(Sunday)'), ('2  October(Wednesday)', '2 October(Wednesday)')], max_length=200, null=True),
        ),
    ]
