# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-09-15 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0047_auto_20190911_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniregistration',
            name='date',
            field=models.CharField(blank=True, choices=[('22 September(Sunday)', '22 September(Sunday)'), ('29 September(Sunday)', '29 September(Sunday)'), ('2  October(Wednesday)', '2 October(Wednesday)')], max_length=200, null=True),
        ),
    ]
