# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-10-02 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0048_auto_20190915_1751'),
        ('Core', '0048_auto_20190927_1327'),
    ]

    operations = [
    ]
