# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-04-16 08:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0049_registration_github_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=39, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-z\\d](?:[a-z\\d]|-(?=[a-z\\d])){0,38}$')]),
        ),
    ]
