# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-04-16 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0050_auto_20200416_1428'),
        ('Core', '0050_auto_20200206_2310'),
    ]

    operations = [
    ]
