# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-04-16 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0051_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='registration',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=39, null=True),
        ),
    ]
