# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-04-16 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0054_auto_20200417_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=39, null=True),
        ),
    ]
