# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-07-31 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0060_remove_registration_fee_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Domain'),
        ),
    ]
