# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-08-01 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0061_auto_20200731_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='other_handles',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='skills',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
