# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-08-01 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0064_auto_20200801_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='other_handles',
            field=models.CharField(blank=True, default=datetime.date(2020, 8, 1), max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='skills',
            field=models.CharField(blank=True, default=datetime.date(2020, 8, 1), max_length=500),
            preserve_default=False,
        ),
    ]
