# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='./static/images'),
        ),
    ]
